### PR TITLE
Support Uuids

### PR DESCRIPTION
**Pull request by thefringeninja**

### CODE REVIEW

**Comment by michaelcfanning** [comment]
I can't believe I missed this PR, my apologies. This is a great change. 

@shaopeng-gh, can you follow up on this merge with some tests that follow the current pattern (for the GUID type)?

**Comment by thefringeninja** [comment]
Thank you!

**Comment by shaopeng-gh** [comment]
Yes, looking.

---
In reply to: [1235685004](https://github.com/microsoft/jschema/pull/132#issuecomment-1235685004) [](http://example.com/codeflow?ancestors=1235685004,1235685004)

**Comment by shaopeng-gh** [comment]
@thefringeninja please review and approve my pull request against your branch: 
https://github.com/thefringeninja/jschema/pull/1

**Comment by shaopeng-gh** [comment]
@michaelcfanning I have fixed the test in his branch, please review.

**Review by shaopeng-gh — APPROVED** [review]
:shipit:

**Pull request merged**
